/* ============================================================
   Turnieje 1.0 — KROKI FLOW (mock). Buduje window.TF_FLOWS:
   { mini: [step...], euro: [step...] }  — kolejność = happy path.
   Ekrany-warianty zakończeń są na końcu listy (poza linią),
   osiągalne przez `variants`/`to`.
   ============================================================ */
(function () {
  const D = window.TF_DATA;

  // skróty zdarzeń (wycinki prasowe) — reużywają EventCard
  const EV = {
    miniFirst: {
      section: 'Zapowiedź kolejki', meta: 'Miniturniej · przed 1. meczem', tone: 'prematch',
      title: 'Pierwszy gwizdek. Czas pokazać skład',
      lead: 'Wydraftowana jedenastka staje przed pierwszym sprawdzianem. Szatnia spięta, ale gotowa.',
      flavor: '„Na rozgrzewce same uśmiechy. Pora zamienić je w punkty.”',
      choices: [
        { letter: 'A', label: 'Spokojne otwarcie', effectHuman: 'Zaczynacie ostrożnie, bez ryzyka.', effectTech: 'Nastawienie: kontrola', tone: 'neutral' },
        { letter: 'B', label: 'Od pierwszej minuty atak', effectHuman: 'Wysoki pressing — chcecie szybkiego gola.', effectTech: 'Nastawienie: ofensywa', tone: 'prematch' },
      ],
      cta: 'Kontynuuj',
    },
    miniDecider: {
      section: 'Raport przedmeczowy', meta: 'Miniturniej · mecz o awans', tone: 'prematch',
      title: 'Mecz o wszystko z Legią',
      match: { round: 'Mecz 3', opponent: 'Wygrana albo remis daje awans. Porażka komplikuje wszystko.' },
      lead: 'Tabela jest ciasna. To spotkanie rozstrzygnie, kto zagra w fazie pucharowej.',
      flavor: '„Trener na konferencji krótko: liczy się tylko jutro.”',
      effect: { human: 'Drużyna gra z podniesionym morale — czuje wagę meczu.', tech: 'Efekt: + mobilizacja' },
      cta: 'Kontynuuj',
    },
    miniPromoted: {
      section: 'Wydanie specjalne', meta: 'Miniturniej · po awansie', tone: 'positive',
      title: 'Awans w kieszeni!',
      lead: 'Twój skład melduje się w fazie pucharowej. Kibice ruszają na trybuny.',
      flavor: '„Szatnia śpiewa. Ale trener styguje emocje — najtrudniejsze przed nami.”',
      effect: { human: 'Pewność siebie rośnie przed półfinałem.', tech: 'Efekt: + morale' },
      cta: 'Do drabinki',
    },
    miniFinal: {
      section: 'Raport przedmeczowy', meta: 'Miniturniej · finał', tone: 'prematch',
      title: 'Finał. Jeden mecz od trofeum',
      match: { round: 'Finał', opponent: 'Naprzeciw Legia — rywal z najlepszą formą.' },
      lead: 'Od draftu do finału. Został ostatni krok.',
      flavor: '„W tunelu cisza. Słychać tylko bicie serc.”',
      effect: { human: 'Maksymalne skupienie — to mecz, na który czekali.', tech: 'Efekt: + koncentracja' },
      cta: 'Wyjdź na finał',
    },
    euFirst: {
      section: 'Zapowiedź turnieju', meta: 'EURO 2016 · przed 1. meczem', tone: 'prematch',
      title: 'Biało-czerwoni wchodzą do gry',
      match: { round: 'Mecz 1', opponent: 'Na start Irlandia Północna — rywal w zasięgu.' },
      lead: 'Cała Polska przed telewizorami. Pierwszy mecz nadaje ton całemu turniejowi.',
      flavor: '„Hymn na pełnych trybunach. Ciarki przechodzą nawet rezerwowym.”',
      choices: [
        { letter: 'A', label: 'Cierpliwa gra', effectHuman: 'Budujecie przewagę powoli i pewnie.', effectTech: 'Nastawienie: kontrola', tone: 'neutral' },
        { letter: 'B', label: 'Wykorzystać nerwy rywala', effectHuman: 'Mocne wejście, by szybko trafić.', effectTech: 'Nastawienie: ofensywa', tone: 'prematch' },
      ],
      cta: 'Kontynuuj',
    },
    euDecider: {
      section: 'Raport przedmeczowy', meta: 'EURO 2016 · mecz o awans', tone: 'prematch',
      title: 'Ukraina. Mecz o awans',
      match: { round: 'Mecz 3', opponent: 'Zwycięstwo niemal pewnie wyprowadza Polskę z grupy.' },
      lead: 'Po remisie z Niemcami cała stawka w meczu z Ukrainą.',
      flavor: '„Na ulicach biało-czerwone flagi. Kraj wstrzymał oddech.”',
      effect: { human: 'Drużyna gra na fali, niesiona przez kibiców.', tech: 'Efekt: + mobilizacja' },
      cta: 'Kontynuuj',
    },
    euPromoted: {
      section: 'Wydanie specjalne', meta: 'EURO 2016 · po awansie', tone: 'positive',
      title: 'Polska w fazie pucharowej!',
      lead: 'Drugie miejsce w grupie C i komplet czystych kont. Marzenie trwa.',
      flavor: '„Komentator nie kryje wzruszenia. To już historia.”',
      effect: { human: 'Cały kraj za plecami drużyny przed 1/8 finału.', tech: 'Efekt: + morale' },
      cta: 'Do drabinki',
    },
    euFinal: {
      section: 'Raport przedmeczowy', meta: 'EURO 2016 · finał', tone: 'prematch',
      title: 'Finał. Jeden mecz od historii',
      match: { round: 'Finał EURO 2016', opponent: 'Naprzeciw gospodarze i ich rozpędzona maszyna.' },
      lead: 'Tu nie ma już jutra — jest tylko ten mecz.',
      flavor: '„W tunelu cisza. Słychać tylko bicie serc.”',
      effect: { human: 'Drużyna gra na maksimum skupienia — mecz życia.', tech: 'Efekt: + koncentracja' },
      cta: 'Wyjdź na finał',
    },
  };

  const F = (res) => res.W ? ['W', res.W[1] || 'R', res.W[2] || 'W'] : ['W', 'R', 'W'];

  // ── MINITURNIEJ ──
  const mini = [
    { id: 'mt-start', type: 'start', kicker: 'Tryb podstawowy', title: 'Miniturniej Ekstraklasy',
      intro: 'Szybki sprawdzian wydraftowanego składu: grupa czterech ekip, a potem faza pucharowa.',
      rules: ['3 mecze w grupie 4 drużyn', 'Tabela na żywo po każdym meczu', 'Dwie najlepsze ekipy grają dalej', 'Półfinał i finał o trofeum'],
      teams: ['TY', 'WIS', 'LEG', 'WID'], you: 'TY', cta: 'Rozpocznij fazę grupową', back: false },
    { id: 'mt-group', type: 'group', kicker: 'Miniturniej · Twoja grupa', title: 'Grupa', rows: D.MT_G0, highlight: 'TY', advance: 2,
      fixtures: [{ when: 'Mecz 1', home: 'TY', away: 'WID', you: 'TY' }, { when: 'Mecz 2', home: 'TY', away: 'WIS', you: 'TY' }, { when: 'Mecz 3', home: 'TY', away: 'LEG', you: 'TY' }],
      tone: 'live', text: 'Faza grupowa przed startem', cta: 'Przed pierwszym meczem' },
    { id: 'mt-ev1', type: 'event', ev: EV.miniFirst },
    { id: 'mt-m1pre', type: 'matchPre', stage: 'Miniturniej · Mecz 1', home: 'TY', away: 'WID', you: 'TY',
      desc: 'Pierwszy sprawdzian wydraftowanej jedenastki.', formHome: ['W', 'W', 'R'], formAway: ['P', 'R', 'P'], cta: 'Rozegraj mecz' },
    { id: 'mt-m1res', type: 'matchRes', stage: 'Miniturniej · Mecz 1', home: 'TY', away: 'WID', score: '2 : 0',
      comment: 'Pewne otwarcie. Twoja jedenastka kontrolowała grę od pierwszej minuty.', cta: 'Zobacz tabelę' },
    { id: 'mt-tab1', type: 'table', kicker: 'Miniturniej · po 1. meczu', title: 'Tabela grupy', rows: D.MT_G1, highlight: 'TY', advance: 2, tone: 'live', text: 'Dobre wejście — tak trzymać' },
    { id: 'mt-m2pre', type: 'matchPre', stage: 'Miniturniej · Mecz 2', home: 'TY', away: 'WIS', you: 'TY',
      desc: 'Wisła postawi twardsze warunki. Trzeba potwierdzić formę.', formHome: ['W', 'W', 'R'], formAway: ['W', 'P', 'R'], cta: 'Rozegraj mecz' },
    { id: 'mt-m2res', type: 'matchRes', stage: 'Miniturniej · Mecz 2', home: 'TY', away: 'WIS', score: '2 : 1',
      comment: 'Walka do końca, ale komplet punktów zostaje u Ciebie.', cta: 'Zobacz tabelę' },
    { id: 'mt-tab2', type: 'table', kicker: 'Miniturniej · po 2. meczu', title: 'Tabela grupy', rows: D.MT_G2, highlight: 'TY', advance: 2, tone: 'good', text: 'Awans coraz bliżej' },
    { id: 'mt-ev2', type: 'event', ev: EV.miniDecider },
    { id: 'mt-m3pre', type: 'matchPre', stage: 'Miniturniej · Mecz 3', home: 'TY', away: 'LEG', you: 'TY',
      desc: 'Mecz o pierwsze miejsce w grupie.', formHome: ['W', 'W', 'W'], formAway: ['W', 'W', 'R'], cta: 'Rozegraj mecz' },
    { id: 'mt-m3res', type: 'matchRes', stage: 'Miniturniej · Mecz 3', home: 'TY', away: 'LEG', score: '2 : 1',
      comment: 'Komplet zwycięstw. Grupa rozbita w pył.', cta: 'Tabela końcowa' },
    { id: 'mt-tab3', type: 'table', kicker: 'Miniturniej · komplet', title: 'Tabela końcowa', rows: D.MT_G3, highlight: 'TY', advance: 2, tone: 'good', text: 'Awans z pierwszego miejsca!',
      cta: 'Zobacz awans', variants: [{ label: 'Pokaż wariant: odpadnięcie z grupy', to: 'mt-end-groupout', tone: 'mute' }] },
    { id: 'mt-advance', type: 'advance', badge: 'Awans', title: 'Awans do fazy pucharowej!', sub: 'Pierwsze miejsce w grupie. Twój skład gra dalej.', rows: D.MT_G3, highlight: 'TY', advance: 2, cta: 'Dalej' },
    { id: 'mt-ev3', type: 'event', ev: EV.miniPromoted },
    { id: 'mt-ladder', type: 'ladder', kicker: 'Miniturniej · faza pucharowa', title: 'Drabinka', steps: D.MT_LADDER('sf'), cta: 'Zagraj półfinał' },
    { id: 'mt-sfpre', type: 'matchPre', stage: 'Miniturniej · Półfinał', home: 'TY', away: 'WIS', you: 'TY',
      desc: 'Rewanż z Wisłą — tym razem o finał.', formHome: ['W', 'W', 'W'], formAway: ['R', 'W', 'P'], cta: 'Rozegraj mecz' },
    { id: 'mt-sfres', type: 'matchRes', stage: 'Miniturniej · Półfinał', home: 'TY', away: 'WIS', score: '2 : 1',
      comment: 'Nerwowa końcówka, ale finał jest Wasz.', cta: 'Dalej' },
    { id: 'mt-ev4', type: 'event', ev: EV.miniFinal },
    { id: 'mt-finalpre', type: 'matchPre', stage: 'Miniturniej · Finał', home: 'TY', away: 'LEG', you: 'TY',
      desc: 'Jeden mecz o trofeum. Wszystko albo nic.', formHome: ['W', 'W', 'W'], formAway: ['W', 'R', 'W'], cta: 'Zagraj finał' },
    { id: 'mt-finalres', type: 'matchRes', stage: 'Miniturniej · Finał', home: 'TY', away: 'LEG', score: '1 : 0',
      comment: 'Jedna bramka, a smakuje jak dziesięć. Trofeum jedzie do Ciebie.', cta: 'Ekran końcowy',
      variants: [{ label: 'Pokaż wariant: porażka w finale', to: 'mt-end-finalloss', tone: 'mute' }] },
    { id: 'mt-end-win', type: 'end', outcome: 'win', pathLabel: 'Twoja droga', headline: 'Miniturniej zdobyty!', sub: 'Twój wydraftowany skład sięga po trofeum bez porażki.',
      path: D.MT_PATH_WIN, bestPlayer: 'Zbigniew Boniek', lineupNote: '4-3-3 · Twój skład',
      comment: 'Od draftu do pucharu. Ta jedenastka udowodniła, że historia może iść po Twojej myśli.', ctaLabel: 'Wróć do huba', to: 'hub' },
    // — warianty zakończeń (poza linią) —
    { id: 'mt-end-finalloss', type: 'end', outcome: 'loss', pathLabel: 'Twoja droga', headline: 'Tak blisko trofeum', sub: 'Porażka 0:1 w finale. Srebro boli, ale ta droga robi wrażenie.',
      path: D.MT_PATH_FINALLOSS, bestPlayer: 'Kazimierz Deyna', lineupNote: '4-3-3 · Twój skład',
      comment: 'Finał przegrany jedną bramką. Wrócicie po więcej.', ctaLabel: 'Nowy draft', to: 'hub' },
    { id: 'mt-end-groupout', type: 'end', outcome: 'loss', pathLabel: 'Twoja droga', headline: 'Koniec już w grupie', sub: 'Trzecie miejsce. Tym razem zabrakło punktów do fazy pucharowej.',
      path: D.MT_PATH_GROUPOUT, bestPlayer: 'Grzegorz Lato', lineupNote: '4-3-3 · Twój skład',
      comment: 'Bywają takie turnieje. Czas na nowy draft i rewanż.', ctaLabel: 'Zagraj ponownie', to: 'hub', altTable: D.MT_OUT, altHighlight: 'TY' },
  ];

  // ── EURO 2016 ──
  const euro = [
    { id: 'eu-intro', type: 'start', kicker: 'Turniej historyczny', title: 'EURO 2016 Retro',
      intro: 'Poprowadź Polskę od grupy C aż do finału. Realne grupy, Twoja droga.',
      rules: ['Grupa C: Polska, Niemcy, Ukraina, Irlandia Płn.', '3 mecze grupowe', 'Dwie najlepsze + najlepsze z 3. miejsc awansują', 'Faza pucharowa: 1/8 → ćwierć → półfinał → finał'],
      teams: ['POL', 'GER', 'UKR', 'NIR'], you: 'POL', cta: 'Rozpocznij EURO 2016', back: false },
    { id: 'eu-group', type: 'group', kicker: 'EURO 2016 · Grupa C', title: 'Grupa C', rows: D.EU_G0, highlight: 'POL', advance: 2, thirdChance: true,
      fixtures: [{ when: 'Mecz 1', home: 'POL', away: 'NIR', you: 'POL' }, { when: 'Mecz 2', home: 'POL', away: 'GER', you: 'POL' }, { when: 'Mecz 3', home: 'POL', away: 'UKR', you: 'POL' }],
      tone: 'live', text: 'Faza grupowa przed startem', cta: 'Przed pierwszym meczem' },
    { id: 'eu-ev1', type: 'event', ev: EV.euFirst },
    { id: 'eu-m1pre', type: 'matchPre', stage: 'Grupa C · Mecz 1', home: 'POL', away: 'NIR', you: 'POL',
      desc: 'Dobry początek to połowa sukcesu.', formHome: ['W', 'R', 'W'], formAway: ['R', 'P', 'W'], cta: 'Rozegraj mecz' },
    { id: 'eu-m1res', type: 'matchRes', stage: 'Grupa C · Mecz 1', home: 'POL', away: 'NIR', score: '1 : 0',
      comment: 'Oszczędne, ale skuteczne. Trzy punkty na dobry początek.', cta: 'Zobacz tabelę' },
    { id: 'eu-tab1', type: 'table', kicker: 'Grupa C · po 1. meczu', title: 'Tabela grupy', rows: D.EU_G1, highlight: 'POL', advance: 2, thirdChance: true, tone: 'good', text: 'Polska w grze o awans' },
    { id: 'eu-m2pre', type: 'matchPre', stage: 'Grupa C · Mecz 2', home: 'POL', away: 'GER', you: 'POL',
      desc: 'Mecz o prestiż i kontrolę nad grupą.', formHome: ['W', 'R', 'W'], formAway: ['W', 'W', 'R'], cta: 'Rozegraj mecz' },
    { id: 'eu-m2res', type: 'matchRes', stage: 'Grupa C · Mecz 2', home: 'POL', away: 'GER', score: '0 : 0',
      comment: 'Bezbramkowy klasyk. Remis z faworytem smakuje jak zwycięstwo.', cta: 'Zobacz tabelę' },
    { id: 'eu-tab2', type: 'table', kicker: 'Grupa C · po 2. meczu', title: 'Tabela grupy', rows: D.EU_G2, highlight: 'POL', advance: 2, thirdChance: true, tone: 'warn', text: 'Wszystko rozstrzygnie ostatni mecz' },
    { id: 'eu-ev2', type: 'event', ev: EV.euDecider },
    { id: 'eu-m3pre', type: 'matchPre', stage: 'Grupa C · Mecz 3', home: 'POL', away: 'UKR', you: 'POL',
      desc: 'Wygrana niemal pewnie daje awans.', formHome: ['W', 'R', 'W'], formAway: ['P', 'P', 'R'], cta: 'Rozegraj mecz' },
    { id: 'eu-m3res', type: 'matchRes', stage: 'Grupa C · Mecz 3', home: 'POL', away: 'UKR', score: '1 : 0',
      comment: 'Znów czyste konto i komplet punktów. Polska wychodzi z grupy.', cta: 'Tabela końcowa' },
    { id: 'eu-tab3', type: 'table', kicker: 'Grupa C · komplet', title: 'Tabela końcowa', rows: D.EU_G3, highlight: 'POL', advance: 2, thirdChance: true, tone: 'good', text: 'Polska wychodzi z grupy!',
      cta: 'Zobacz awans', variants: [{ label: 'Wariant: awans z 3. miejsca', to: 'eu-advance-third', tone: 'mute' }, { label: 'Wariant: odpadnięcie w grupie', to: 'eu-end-groupout', tone: 'mute' }] },
    { id: 'eu-advance', type: 'advance', badge: 'Awans', title: 'Polska w fazie pucharowej!', sub: 'Drugie miejsce w grupie C, komplet czystych kont.', rows: D.EU_G3, highlight: 'POL', advance: 2, thirdChance: true, cta: 'Dalej' },
    { id: 'eu-ev3', type: 'event', ev: EV.euPromoted },
    { id: 'eu-ladder', type: 'ladder', kicker: 'EURO 2016 · faza pucharowa', title: 'Droga Polski', steps: D.EU_LADDER('r16'), cta: 'Zagraj 1/8 finału' },
    { id: 'eu-r16pre', type: 'matchPre', stage: '1/8 finału', home: 'POL', away: 'SUI', you: 'POL',
      desc: 'Szwajcaria — równy, niewygodny rywal.', formHome: ['W', 'R', 'W'], formAway: ['W', 'W', 'R'], cta: 'Rozegraj mecz' },
    { id: 'eu-r16res', type: 'matchRes', stage: '1/8 finału', home: 'POL', away: 'SUI', score: '1:1 k.',
      comment: 'Po dogrywce decydują karne — i nerwy ze stali. Jest ćwierćfinał!', cta: 'Dalej',
      variants: [{ label: 'Pokaż wariant: odpadnięcie w 1/8', to: 'eu-end-r16', tone: 'mute' }] },
    { id: 'eu-qfpre', type: 'matchPre', stage: 'Ćwierćfinał', home: 'POL', away: 'POR', you: 'POL',
      desc: 'Portugalia z gwiazdą w składzie. Mecz marzeń.', formHome: ['W', 'R', 'W'], formAway: ['W', 'W', 'W'], cta: 'Rozegraj mecz' },
    { id: 'eu-qfres', type: 'matchRes', stage: 'Ćwierćfinał', home: 'POL', away: 'POR', score: '2 : 1',
      comment: 'Odważny mecz nagrodzony. Polska w półfinale EURO!', cta: 'Dalej',
      variants: [{ label: 'Pokaż wariant: odpadnięcie w ćwierćfinale', to: 'eu-end-qf', tone: 'mute' }] },
    { id: 'eu-sfpre', type: 'matchPre', stage: 'Półfinał', home: 'POL', away: 'GER', you: 'POL',
      desc: 'Rewanż z Niemcami — tym razem o finał.', formHome: ['W', 'W', 'W'], formAway: ['W', 'W', 'R'], cta: 'Rozegraj mecz' },
    { id: 'eu-sfres', type: 'matchRes', stage: 'Półfinał', home: 'POL', away: 'GER', score: '1 : 0',
      comment: 'Jeden cios wystarczył. Polska w finale EURO 2016!', cta: 'Dalej',
      variants: [{ label: 'Pokaż wariant: odpadnięcie w półfinale', to: 'eu-end-sf', tone: 'mute' }] },
    { id: 'eu-ev4', type: 'event', ev: EV.euFinal },
    { id: 'eu-finalpre', type: 'matchPre', stage: 'Finał EURO 2016', home: 'POL', away: 'FRA', you: 'POL',
      desc: 'Gospodarze i ich rozpędzona maszyna. Mecz życia.', formHome: ['W', 'W', 'W'], formAway: ['W', 'W', 'W'], cta: 'Zagraj finał' },
    { id: 'eu-finalres', type: 'matchRes', stage: 'Finał EURO 2016', home: 'POL', away: 'FRA', score: '2 : 1',
      comment: 'Niemożliwe stało się faktem. Polska na szczycie Europy!', cta: 'Ekran końcowy',
      variants: [{ label: 'Pokaż wariant: porażka w finale', to: 'eu-end-finalloss', tone: 'mute' }] },
    { id: 'eu-end-win', type: 'end', outcome: 'win', headline: 'Historia napisana na nowo', sub: 'Biało-czerwoni sięgają po EURO 2016 Retro. Niemożliwe stało się faktem.',
      path: D.EU_PATH.champ, bestPlayer: 'Włodzimierz Lubański', lineupNote: '4-3-3 · Złota Jedenastka',
      comment: 'Tego scenariusza nie wymyśliłby żaden dziennikarz. A jednak — Polska na szczycie Europy.', ctaLabel: 'Wróć do huba', to: 'hub' },
    // — warianty zakończeń (poza linią) —
    { id: 'eu-advance-third', type: 'advance', badge: 'Awans z 3. miejsca', title: 'Polska awansuje z 3. miejsca!', sub: 'Trzecie miejsce w grupie C, ale dorobek punktowy wystarcza wśród najlepszych ekip z 3. miejsc.', rows: D.EU_THIRD, highlight: 'POL', advance: 2, thirdChance: true, cta: 'Dalej', to: 'eu-ev3' },
    { id: 'eu-end-finalloss', type: 'end', outcome: 'loss', headline: 'Srebro ze złotym posmakiem', sub: 'Porażka 0:1 w finale. Polska jak nigdy blisko korony Europy.',
      path: D.EU_PATH.finalLoss, bestPlayer: 'Grzegorz Lato', lineupNote: '4-3-3 · Twój skład',
      comment: 'Finał EURO i jedna bramka różnicy. Tej drogi nikt nie zapomni.', ctaLabel: 'Wróć do huba', to: 'hub' },
    { id: 'eu-end-sf', type: 'end', outcome: 'loss', headline: 'Tak blisko finału', sub: 'Porażka w półfinale. Marzenie o finale prysło o włos.',
      path: D.EU_PATH.sf, bestPlayer: 'Jan Tomaszewski', lineupNote: '4-3-3 · Twój skład',
      comment: 'Półfinał EURO to wynik, o jakim marzono latami. Głowy do góry.', ctaLabel: 'Wróć do huba', to: 'hub' },
    { id: 'eu-end-qf', type: 'end', outcome: 'loss', headline: 'Karny dramat w ćwierćfinale', sub: 'Koniec po rzutach karnych. Odważny bój nagrodzony szacunkiem.',
      path: D.EU_PATH.qf, bestPlayer: 'Jan Tomaszewski', lineupNote: '4-3-3 · Twój skład',
      comment: 'Karne to loteria, ale charakteru tej drużynie nikt nie odbierze.', ctaLabel: 'Wróć do huba', to: 'hub' },
    { id: 'eu-end-r16', type: 'end', outcome: 'loss', headline: 'Koniec w 1/8 finału', sub: 'Porażka 0:1 w pierwszej fazie pucharowej. Awans z grupy i tak był sukcesem.',
      path: D.EU_PATH.r16, bestPlayer: 'Robert Lewandowski', lineupNote: '4-3-3 · Twój skład',
      comment: 'Pierwsza runda pucharowa za twarda. Ale grupa pokazała charakter.', ctaLabel: 'Wróć do huba', to: 'hub' },
    { id: 'eu-end-groupout', type: 'end', outcome: 'loss', headline: 'Koniec już w grupie', sub: 'Trudny los grupy C okazał się za ciężki. Pożegnanie po fazie grupowej.',
      path: D.EU_PATH.groupOut, bestPlayer: 'Grzegorz Lato', lineupNote: '4-3-3 · Twój skład',
      comment: 'Bywają grupy, z których nie ma łatwego wyjścia. Wracamy po naukę.', ctaLabel: 'Wróć do huba', to: 'hub', altTable: D.EU_OUT, altHighlight: 'POL' },
  ];

  window.TF_FLOWS = { mini, euro };
})();
